fix(@clayui/drop-down): Adds missing export of IProps on Menu
Before that, this error was occuring:

```
$ cross-env NODE_ENV=production tsc --project ./tsconfig.declarations.json
src/drilldown/index.tsx(21,1): error TS4082: Default export of the module has or is using private name 'IProps'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```